sudo: false
language: ruby
cache: bundler

install:
  # If we're running for a pull request, check out the revision of sass-spec
  # referenced by that pull request.
  - |
    if [ ! -z "$TRAVIS_PULL_REQUEST" -a "$TRAVIS_PULL_REQUEST" != false ]; then
      ref=$(extra/sass-spec-ref.sh)
      mkdir sass-spec
      git -C sass-spec init
      git -C sass-spec pull --depth=1 git://github.com/sass/sass-spec "$ref"
      bundle config local.sass-spec "$(pwd)/sass-spec"
    fi

  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle update sass-spec
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
gemfile: Gemfile
branches:
  only:
    - master
    - stable
    - stable_3_2
    - next
notifications:
  irc: {channels: "irc.freenode.org#sass"}
